[default]

locale = "en-au"
extend-ignore-re = [
  # spellchecker:disable-line
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"
]

[default.extend-words]

center = "center"
customizations = "customizations"
customizing = "customizing"
humanize = "humanize"
maximize = "maximize"
maximizes = "maximizes"
maximizing = "maximizing"
prioritizing = "prioritizing"
recognize = "recognize"
synchronize = "synchronize"
initializing = "initializing"

[files]

ignore-vcs = true

extend-exclude = [
  ".git",
  "_vendor",
  "go.mod",
  "go.sum",
  "static/**",
  "themes/**",
  "vendor/**",
]
