---
##################################################
# Name: update.yaml
# Description: Workflow for Updating Developer Environment
##################################################

name: Devenv Update

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: read

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1

defaults:
  run:
    shell: bash

jobs:
  ##################################################
  # Update
  ##################################################

  update:
    name: Update

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: false
          submodules: recursive

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          enable_kvm: true

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v17
        if: vars.CACHIX_CACHE_NAME != ''
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: cachix_tools_install
        name: Install Cachix Tools
        run: |
          nix profile install --accept-flake-config nixpkgs#devenv

      - id: devenv_gc
        name: Devenv gc
        run: |
          devenv --no-tui gc

      - id: devenv_update
        name: Devenv update
        run: |
          devenv --no-tui update

      - id: devenv_test
        name: Devenv test
        run: |
          devenv --no-tui test

      - id: create_pull_request
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update devenv.lock"
          title: "chore: Update devenv.lock"
          body: "This PR updates the devenv input dependencies"
          branch: "update-devenv-lock"
          base: ${{ env.BRANCH_NAME_DEFAULT }}
          labels: "dependencies"
          assignees: "MAHDTech"
          reviewers: "MAHDTech"
          draft: false
          signoff: true
          delete-branch: true
          sign-commits: true
