---
##################################################
# Name: pages.yaml
# Description:
#   A Workflow that publishes Cloudflare Pages using Wrangler.
##################################################

name: Cloudflare Pages

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  # Automatically run anytime there
  # is a push to the default branch
  push:
    branches:
      - trunk

  # Automatically run anytime a PR
  # targets the default branch
  # for the defined types.
  pull_request:
    branches:
      - trunk
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested

  # Re-build every week to ensure
  # the workers still builds as external
  # dependencies change.
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write
  checks: read
  statuses: read
  deployments: write

defaults:
  run:
    shell: bash

env:
  # Cloudflare account details.
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_TOKEN_WRANGLER: ${{ secrets.CLOUDFLARE_WORKERS_TOKEN }}
  CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}

  PAGES_PROJECT_NAME: tresr-community

  # Enable or disable Cloudflare KV and R2
  CLOUDFLARE_KV_ENABLED: FALSE
  CLOUDFLARE_R2_ENABLED: TRUE

  # GitHUb details.
  ORGANISATION: ${{ github.repository_owner }}
  PROJECT: ${{ github.event.repository.name }}

  # Works on pushes or PRs
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

jobs:
  ##################################################
  # Build and Deploy Cloudflare Pages and Workers
  ##################################################

  wrangler:
    name: Wrangler Deploy

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          lfs: false
          persist-credentials: true
          submodules: recursive

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          enable_kvm: true

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v15
        if: vars.CACHIX_CACHE_NAME != ''
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: cache
        name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - id: devenv_install
        name: Devenv install
        run: |
          nix profile install --accept-flake-config nixpkgs#devenv

      - id: hugo_cleanup
        name: Remove unwanted Hugo files before build
        run: |
          rm -f themes/*/exampleSite || echo "Failed to remove exampleSite from theme"
          rm -f themes/*/content/post/* || echo "Failed to remove posts from theme"
          rm -f themes/*/data/authors/* || echo "Failed to remove authors from theme"
          rm -rf assets/images/backup || echo "Failed to remove extra images"
          rm -rf static/images/backup || echo "Failed to remove extra images"

      - id: hugo_modules
        name: Download Hugo modules
        shell: devenv shell --quiet bash -- -e {0}
        run: |
          if [[ -f package.json ]]; then
            echo "Running npm install"
            npm install
          fi
          if [[ -f "go.mod" ]]; then
            echo "Downloading go modules"
            go mod download -x
          else
            echo "No go.mod file found"
          fi
          echo "Downloading Hugo modules"
          hugo mod get ./...
          hugo mod graph

      - id: get_environment
        name: Get Environment
        run: |
          if [[ "${{ env.BRANCH_NAME_CURRENT }}" == "${{ env.BRANCH_NAME_DEFAULT }}" ]];
          then
            echo "Environment: Production"
            echo "WRANGLER_ENVIRONMENT=production" >> "${GITHUB_OUTPUT}"
          else
            echo "Environment: Preview"
            echo "WRANGLER_ENVIRONMENT=preview" >> "${GITHUB_OUTPUT}"
          fi

      #########################
      # Preview
      #########################

      - id: hugo_build_preview
        name: Build the website using Hugo (Preview)
        if: env.BRANCH_NAME_CURRENT != env.BRANCH_NAME_DEFAULT
        shell: devenv shell --quiet bash -- -e {0}
        env:
          TZ: "Australia/Sydney"
        run: |
          hugo --gc --minify --cleanDestinationDir --environment preview
          touch public/.nojekyll
          ls -la public/

      #########################
      # Production
      #########################

      - id: hugo_build_production
        if: env.BRANCH_NAME_CURRENT == env.BRANCH_NAME_DEFAULT
        name: Build the website using Hugo (Production)
        shell: devenv shell --quiet bash -- -e {0}
        env:
          TZ: "Australia/Sydney"
        run: |
          hugo --gc --minify --cleanDestinationDir --environment production
          touch public/.nojekyll
          ls -la public/

      #########################
      # Deploy
      #########################

      - id: wrangler_deploy
        name: Wrangler deploy ${{ steps.get_environment.outputs.WRANGLER_ENVIRONMENT }}
        shell: devenv shell --quiet bash -- -e {0}
        env:
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_TOKEN_WRANGLER }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy public \
            --project-name ${{ env.PAGES_PROJECT_NAME }} \
            --branch ${{ steps.get_environment.outputs.WRANGLER_ENVIRONMENT }}
